version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/usr/src/onestore_ecommerce/
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
  db:
    image: postgres:14.15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data: